# Utilisez une image Python officielle comme image parente
FROM python:3.11

# Définissez le répertoire de travail sur /app
WORKDIR /app

# Copiez le contenu du répertoire courant dans le conteneur dans /app
COPY . /app

# Installez les packages nécessaires spécifiés dans requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Rendez le port 80 disponible pour le monde extérieur à ce conteneur
EXPOSE 8080

# Exécutez app.py lorsque le conteneur est lancé
CMD ["python", "app.py"]

