version: '3.8'

services:
  redis:
    image: redis
    networks:
      - backend
    deploy:
      replicas: 1 

  db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      replicas: 1  

  vote:
    image: noahdijx/vote:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - frontend
      - backend
    deploy:
      replicas: 3 

  worker:
    image: noahdijx/worker:latest
    depends_on:
      - redis
      - db
    networks:
      - backend
    deploy:
      replicas: 3 

  result-app:
    image: noahdijx/result-app:latest
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - frontend
      - backend
    deploy:
      replicas: 2 

volumes:
  postgres_data:

networks:
  frontend:
  backend:

