version: '3'

services:
  redis:
    image: redis
    networks:
      - backend

  db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    networks:
      - backend

  vote:
    build:
      context: ./vote
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - frontend
      - backend

  worker:
    build:
      context: ./worker
    depends_on:
      - redis
      - db
    networks:
      - backend

  result-app:
    build:
      context: ./result
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - frontend
      - backend

volumes:
  postgres_data:

networks:
  frontend:
  backend:

