version: '3'

services:
  redis:
    image: redis:latest
    networks:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: examplepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Pour persister les données
    networks:
      - backend

  vote:
    build:
      context: ./vote
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - frontend
      - backend

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - redis
      - db
    networks:
      - backend

  result-app:
    build:
      context: ./result
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - frontend
      - backend

volumes:
  postgres_data:
    driver: local

networks:
  frontend:
  backend:

